### PR TITLE
Add Discord badge to README

### PR DESCRIPTION
**Pull request by stephanebruckert**
@dieser-niko and I have set up a Discord server. Just adding the badge from https://github.com/gitlimes/discord-md-badge

Its purpose isn't to replace GitHub issues or existing documentation/examples. Instead, it's for quicker assistance or when creating a GitHub issue might not seem necessary. If a topic is important, we might still ask you to create a GitHub issue for it.

When you join, please read the rules and request any suggestions #server-requests. If you can, set your server username to match your GitHub username so it's easier to link each other to existing contributions.

@plamere if you can join, we will make you an admin as well.

### CODE REVIEW

**Comment by dieser-niko** [comment]
Instead of gitlimes we could also use [shields.io](https://shields.io) instead, just to name an alternative.

**Comment by dieser-niko** [comment]
So it seems that if I'm trying to use shields.io, not only do I need to add the server ID + enable widgets in Discord, but I also need to add an extra invite link. That's one more attribute compared to gitlimes.

**Comment by stephanebruckert** [comment]
Yeah shields.io looks better, I replaced it

**Review by dieser-niko — APPROVED** [review]
We should probably mention the server in the next release as well.

**Pull request merged**
