### PR TITLE
Audiobook Support and CI Workflow Update

### PR DESCRIPTION
**Pull request by danhjoseph**
I have added audiobook support, users can now access single audiobooks, lists of audiobooks, and detailed chapter information. Additionally, I updated the CI workflow due to Python 2.7's sunset, the unavailability of Python 3.6 in GitHub Actions, and the lack of support for Python 2.7 in Ubuntu 20.04.

### CODE REVIEW

**Comment by stephanebruckert** [comment]
Nice! A chance for added integration tests?

**Comment by danhjoseph** [comment]
Yes, no problem. Integration tests will be added in the latest commit.

**Comment by danhjoseph** [comment]
Is it possible to re-run the integration tests action? I've successfully passed the tests locally, and the same failing test passed in the previous commit. I suspect the problem may be due to a timeout issue between GitHub and Spotify.

**Review by stephanebruckert — APPROVED** [review]
Awesome thanks a lot for the tests. I will look at some other PRs and try to release this soon

**Pull request merged**
