### PR TITLE
Update Directions In TUTORIAL.md; Add Unit Tests To non_user_endpoints test.py

### PR DESCRIPTION
**Pull request by brennanpate**
Hello,

Please note that this is a new pull request that was adapted from the following pull request, which I have since closed: https://github.com/spotipy-dev/spotipy/pull/1101

**Key Changes**

- Updated order of instructions for Python and pip package manager installation in TUTORIAL.md
- Updated TUTORIAL.md instructions to match current layout of Spotify Developer Dashboard
- Added test_artist_id, test_artist_url, and test_artists_mixed_ids to non_user_endpoints test.py

Please let me know if there are any changes needed or any questions.

Thank you!

### CODE REVIEW

**Comment by dieser-niko** [comment]
It seems like you've removed a lot of line endings (LF). Can you explain why?

**Comment by brennanpate** [comment]
> It seems like you've removed a lot of line endings (LF). Can you explain why?

Hi Niko,

I apologize if I'm misunderstanding, but is this referring to added empty lines like in tests.py?

files-changed-tests

Just want to make sure I understand and am happy to make any needed changes.

Thank you!

**Comment by dieser-niko** [comment]
No, they are fine. I'll revert this change, so you can see what I mean.

**Comment by brennanpate** [comment]
> No, they are fine. I'll revert this change, so you can see what I mean.

Hi Niko,

Thank you for showing me this. Removing the line endings in CHANGELOG.md, CONTRIBUTING.md, and docs/requirements.txt was not intentional.

Would you like for me to add the line endings highlighted in your commit add17c1 and push my changes?

Thank you!

**Comment by dieser-niko** [comment]
I mean, I've already added the line endings for you, so you don't have to do it. I'll do one more check and merge it if everything is fine.

**Comment by dieser-niko** [comment]
Btw don't worry about the failing integration tests, the audiobooks are only available in some regions.

**Review by dieser-niko — APPROVED** [review]

**Comment by brennanpate** [comment]
> Btw don't worry about the failing integration tests, the audiobooks are only available in some regions.

Noted about the integration tests. Thank you for reviewing my pull request, Niko!

**Pull request merged**
